//
// Created by vscode on 4/11/26.
//

#ifndef NEEDYRESOURCES_MESSAGE_FRAME_TYPE_H
#define NEEDYRESOURCES_MESSAGE_FRAME_TYPE_H
typedef enum {
    RESOURCE_REQUEST,
    CLIENT_CONNECTION,_REQQUEST,CCLI
} needy_message_type;
#endif //NEEDYRESOURCES_MESSAGE_FRAME_TYPE_H
