#ifndef NEEDYRESOURCES_MESSAGE_FRAME_TYPE_H
#define NEEDYRESOURCES_MESSAGE_FRAME_TYPE_H
typedef enum {
    RESOURCE_REQUEST,
    CLIENT_CONNECTION_REQUEST,
    SERVER_ACK,
    CLIENT_FINALIZE
} needy_message_type;
#endif //NEEDYRESOURCES_MESSAGE_FRAME_TYPE_H
